default: &default
  adapter: postgresql
  encoding: utf8
  pool: 15
  timeout: 30000
  host: localhost
  database: twitter_feeds
  username: twitter_feeds
  password: TtwwiittPpaass

development:
  <<: *default

local:
  <<: *default
  adapter: mysql2
test:
  <<: *default
  database: twitter_feeds_test
  password: TtwwiittPpaass

production:
  <<: *default
  database: <%= ENV['PROD_DB_NAME'] %>
  username: <%= ENV['PROD_DB_USERNAME'] %>
  password: <%= ENV['PROD_DB_PASSWORD'] %>
